export const metadata = {
  title: 'Shop',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        {children}
        </body>
    </html>
  )
}
